### ISSUE TITLE
Slow performance, roughly half speed

### ISSUE THREAD

**Issue by weirdo6666** [eternaldensity/Sandcastle-Builder#1288]
The game recently slowed down dramatically for me.  I timed 18 seconds, but instead of 10 mNP advanced, it was only 5.  I noticed it right after getting the HAL-0-Kitty boost, but it's possible that it was already slow, and I just didn't notice.  I played the game roughly to this point before (I had recently gotten HAL-0-Kitty there too) and experienced similarly slow performance, but things went back to normal speed after I did Molpy Down.

**Comment by weirdo6666** [comment]
I did an export/import to move from Chrome to IE, and it was slow there too.  Here's the export string:

My42NjAzUFAxNDIxNDQ1MTE1NjAxUDAxOTAwMDAxMDAwMDAxMDAwMDAzMTAwUDI0MlMxNDY4NDFTMTAxUzEwUzFTMjNTMjRTNzY5NlMxUzEyNVMxNzRTMFMyNFMyOTJTMFMwUzk5U1AxNEMxNEMyMTM1ODAzMy44MjUwMjgzMjZDMEMwUzE0QzE1QzgyMzQyNDkuNjMwMDM4NzVDMEMwUzE0QzE0QzM3OTAzMDBDMEMwUzBDMEMwQzBDMFMwQzBDMEMwQzBTMEMwQzBDMEMwU1AxN0MxN0M0MTIyMEMwQzBDMEMwQzBDMFMxNEMxNEMxNTkxMEMyNDUwQzBDMEMwQzBDMFM0QzRDOTEwOEMyNDg0QzRDMEMwQzBDMFM1QzVDNDQ0NjBDODIwOEMwQzBDMEMwQzBTMEMwQzBDMEMwQzBDMEMwQzBTMEMwQzBDMEMwQzBDMEMwQzBTUDFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzBDMEMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMUMwUzFDMUMyQzBTMEMwQzBDMFMxQzFDMEMwUzBDMEMwQzBTMUMxQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwLjRDMFMwQzBDMS41QzBTMEMwQzBDMFMwQzBDMEMwUzFDMUMxQzBDMTZTMEMwQzBDMFMwQzBDMEMwUzFDMUMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMwQzBDMEMwUzBDMEMwQzBTMUMxQzBDMFMxQzFDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzFDMUMwQzBTMEMwQzBDMFMwQzBDMEMwUzFDMUMxM0MwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMUMxQzFDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBDMVMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwQzBTMEMwQzBDMEMwUzBDMEMwQzBDMFMwQzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMUMxQzFDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzQwMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMxQzFDMUMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzFDMUM4MTMxNi45NTQwNjAzNzA2NkMwQzU5NDQyODUzLjk1NDA4NTU5Qzk2MTkwNEMxODY3NDk2LjAzMzk5OTUzNFMxQzFDNzE1QzBDMTA1NTkzQzEzMjI2QzEyMTk0M0M5MTY1MkMxOTY0MThDMzE3ODExUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwQzBTMEMwQzBDMEMwQzBDMEMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMEMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMUMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMEMwQzBTMEMwQzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwQzBDMFMwQzBDMEMwQzBDMFMwQzBDMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMEMwUzBDMEMwQzBTMUMxQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwU1AxMTExMTExMTExMTExMTAwMTAwMDAxMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTEwMDAwMDAwMTExMDExMTAxMTEwMTAwMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMFBQMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwUFA=

**Comment by eternaldensity** [comment]
Looks like you've discovered longpix.

**Comment by weirdo6666** [comment]
Derp.  So I have.
