### ISSUE TITLE
Cut diamonds. add a max function?

### ISSUE THREAD

**Issue by EPSIL0N** [eternaldensity/Sandcastle-Builder#1298]
Saw another complaint on reddit about buying cut diamonds and having the rate decrease because of a low number of finds. Did we want to add a max function to always award the larger of the two amounts in those cases?

**Comment by TheSnacker** [comment]
That would also make clicking the beach worth it after getting Cut Diamonds, so I say go for it.  If you want, I can take care of it tonight.  I need to get a testing setup put together at home anyway.  If I plan to take a more active role, I can't do everything during my lunch hour.

**Comment by EPSIL0N** [comment]
I have no clue who is still around as the github and reddit have been so quiet. I could do it or you if you find yourself working on the code, I couldn't imagine any reason not to add one but figured I should ask.

**Comment by TheSnacker** [comment]
I added it.

**Comment by EPSIL0N** [comment]
Looks like this issue is finished

**Comment by eternaldensity** [comment]
Oops I meant to close it.
Sent from the air between Dubai and Frankfurt.
