### ISSUE TITLE
"Tesseract" is misspelled - is renaming boosts straightforward?

### ISSUE THREAD

**Issue by Calamitizer** [eternaldensity/Sandcastle-Builder#1335]
It's spelled as "tessaract" in-game. Is it safe to just change every string of "tessaract" into "tesseract" in the entire code? A player's owned boosts would be stored by ID, not name, right? I'm just worried about the game knowing it's the same boost. If it's that simple, I'll take care of it (I'm doing a lot of other spelling/grammar/typo fixes).

**Comment by LuminousLeopards** [comment]
Yep, you can change pretty much anything about a boost except its order in the code. You can always test things on a local copy to see whether they break anything.

**Comment by Calamitizer** [comment]
Thanks! Done.
