### ISSUE TITLE
Save sync mechanism

### ISSUE THREAD

**Issue by erp-lsf** [eternaldensity/Sandcastle-Builder#1363]
How would you like idea of having your save files synced across different browsers/PCs via, for example, gists? Although it would require use of third-party JS library (I'm not considering reinventing the bicycle again now), I'm willing to implement this, at least for my own use.

**Comment by Calamitizer** [comment]
That sounds great! Except we should make sure to preserve the ability to have multiple saves (i.e. be able to disable the autosync once it's enabled).

**Comment by erp-lsf** [comment]
Actually, I'm thinking about commits(if it will use repository) for every, 10-n, saves.

**Comment by eternaldensity** [comment]
The idea is attractive.

**Comment by EPSIL0N** [comment]
I'm all for something on top of the regular ability to save but I often go offline so the ability to export to text and save in a local document is crucial to me.

**Comment by eternaldensity** [comment]
> I'm all for something on top of the regular ability to save but I often go offline so the ability to export to text and save in a local document is crucial to me.

We've already got that and wouldn't be removing it.

**Comment by EPSIL0N** [comment]
Ah, just general disaster proofing, I am certain I've set my computer to not delete the cookies or local storage or wherever but I sleep easier knowing I have the text strings saved.

Was just saying that I need the text saves as the perfect synch saving system is less useful if I am forced offline for extended periods.

**Comment by erp-lsf** [comment]
Should I create new file in a gist for each save, or just change contents of single file?
And won't you mind providing credentials or your accounts, or should sync mechanism should be anonymous? 
Right now it creates a single private gist, and then stores each  save in new file.
