### ISSUE TITLE
It's possible to buy big teeth/camelflarge without diamonds

### ISSUE THREAD

**Issue by pickten** [eternaldensity/Sandcastle-Builder#1368]
As above. I don't have diamonds (not even the Stuff), but something caused the price to become free and buying worked.

Sample diamondless tooth-owning save:

My42NjdQUDE0MzMzNzk0NjcwNTBQMDAyMDAwMDE1NTAxMDEwMDAwMDMwMjBQMjE5M1MyNTIwNzcyUzIyNFMwUzFTMzA2Uzg0UzI5MTAxMjZTMFMyUzM2UzBTMjI4NDQwUzIxOTNTMFM1NVMyMFNQSW5maW5pdHlDNy4xNTU3MDQ2MjI2NTgyODllJTI1MkI1N0NJbmZpbml0eUNJbmZpbml0eUNJbmZpbml0eVNJbmZpbml0eUM3LjE1NTcwNDYyMjY1ODI4OWUlMjUyQjU3Q0luZmluaXR5Q0luZmluaXR5Q0luZmluaXR5U0luZmluaXR5QzcuMTU1NzA0NjIyNjU4Mjg5ZSUyNTJCNTdDSW5maW5pdHlDSW5maW5pdHlDSW5maW5pdHlTSW5maW5pdHlDNy4xNTU3MDQ2MjI2NTgyODllJTI1MkI1N0NJbmZpbml0eUNJbmZpbml0eUNJbmZpbml0eVNJbmZpbml0eUM3LjE1NTcwNDYyMjY1ODI4OWUlMjUyQjU3Q0luZmluaXR5Q0luZmluaXR5Q0luZmluaXR5U0luZmluaXR5QzcuMTU1NzA0NjIyNjU4Mjg5ZSUyNTJCNTdDSW5maW5pdHlDSW5maW5pdHlDSW5maW5pdHlTUEluZmluaXR5QzcuMTU1NzA0NjIyNjU4Mjg5ZSUyNTJCNTdDSW5maW5pdHlDSW5maW5pdHlDMENJbmZpbml0eUNJbmZpbml0eUNJbmZpbml0eUMwU0luZmluaXR5QzcuMTU1NzA0NjIyNjU4Mjg5ZSUyNTJCNTdDTmFOQzUuNzY1NjE1NjUxNzkxODFlJTI1MkIzMEMwQzBDSW5maW5pdHlDSW5maW5pdHlDSW5maW5pdHlTSW5maW5pdHlDNy4xNTU3MDQ2MjI2NTgyODllJTI1MkI1N0MwQzBDMEMwQ0luZmluaXR5Q05hTkNJbmZpbml0eVNJbmZpbml0eUM3LjE1NTcwNDYyMjY1ODI4OWUlMjUyQjU3QzBDMEMwQzBDSW5maW5pdHlDSW5maW5pdHlDSW5maW5pdHlTSW5maW5pdHlDNy4xNTU3MDQ2MjI2NTgyODllJTI1MkI1N0MwQzBDMEMwQ0luZmluaXR5Q0luZmluaXR5Q0luZmluaXR5U0luZmluaXR5QzcuMTU1NzA0NjIyNjU4Mjg5ZSUyNTJCNTdDMEMwQzBDMENJbmZpbml0eUNOYU5DSW5maW5pdHlTUDFDMUMwQzBTMUMxQy0yNDBDMFMxQzFDLTIzOUMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzBDMEMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMUMwUzFDMUMyQzBTMEMwQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMEMwQzJDMFMxQzFDMEMwUzBDMEMwQzBTMUMxQzEuNUMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMUMwQzI5NzRTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzE2QzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMEMwQzExNzRDMFMxQzFDMTNDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzBDMEMwQzBTMUMxQzY2NTU4OUMwUzBDMEMwQzBTMUMxQzM0NEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzExMUMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMTI1OTI3QzBTMUMxQzFDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMEMwQzBDMFMxQzFDMUMwUzBDMEMwQzBTMUMxQ0luZmluaXR5QzBTMUNJbmZpbml0eUNJbmZpbml0eUMwUzFDMUMxQzBTMEMwQzBDMFMxQzFDSW5maW5pdHlDMFMxQzkuNzExNDI2NTgwMTU5MjIzZSUyNTJCMzA2Q0luZmluaXR5QzBDSW5maW5pdHlTMUMxQ0luZmluaXR5QzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzMzMjc5NUMwUzFDMUMwQzBTMUMxQzFDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzFDMFMxQzFDMEMwUzFDMUMxQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzFDMFMxQzFDMEMwUzFDMUMwQzBTMUMyNTIwMjc1MjA4MjYwNjM3MkMxMjYwMTM3NjA0MTMwMzE4NjBDMFMxQzFDMEMwUzBDMEM1MEMwUzFDMUMxMjI4OTAxQzBTMUMxQzBDMFMxQzFDdW5kZWZpbmVkQzk4OThTMEMwQ0luZmluaXR5QzBDMTY2OVMwQzBDMEMwUzFDMUMwQzBTMUMxQ0luZmluaXR5QzBTMUMxQzBDMEM5UzFDMUMwQzBTMUMxQzFDMFMxQzFDMUMwUzFDMUMxQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUNJbmZpbml0eUMwUzBDMEMwQzBTMUMxQzBDMEMwUzFDMUMwQzBDMFMxQzFDMEMwQzBTMUMxQzBDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzEwMjlDMEMwUzFDMTM0QzBDMFMxQzFDMEMwQ05hTkNJbmZpbml0eUNJbmZpbml0eVMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMxQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMwQzBDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUNJbmZpbml0eUMwUzFDMUM2MTkyQzBTMUMxQzBDMFMwQzBDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUM2ZSUyNTJCNTFDMFMwQzBDMEMwUzFDMUMwQzBTMUMxQzFDMFMxQzFDMEMwUzBDMEMwQzBTMUMxQzEyMTc0MDAwMDBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMyMy45ODgwNTMzODE0NDMwMjRDMFMxQzFDMzQwLjI3NzY3NzE4MjEwODE2QzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQ0luZmluaXR5QzBTMUMxQzFDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUNJbmZpbml0eUMwUzFDMUMwQzBTMUM0QzBDMFMxQzFDMEMwUzFDMUMwQzBTMEMwQzBDMFMxQzFDMzQwMDAwMEMwUzFDMTA1OEMxMDU3QzBTMUMxQzBDMFMwQzBDMEMwUzFDMUMxMDYwNzEyODdDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzFDMFMxQzFDMUMwUzFDMUMtMUMwUzFDMUMwQzBTMUMxQzFDMFMxQzFDMEMwUzFDM0MxNDIwMjZDMFMxQzBDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzMzMjc5NEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBDSW5maW5pdHlDSW5maW5pdHlDMTI1MDc5MjU5MTc4MDMuNDAyUzFDMUMwQzBDSW5maW5pdHlDTmFOQzEuNzk3NjkzMTM0ODYyMzE1N2UlMjUyQjMwOENJbmZpbml0eUMxQzFTMUMxQzBDMFMxQzFDMTE0NTcyNTg4NTAzQzBTMUMxQzEwOTJDMFMxQzFDMUMwUzFDMUM2ODUwODFDMFMxQzFDNTBDMEMzLjE0MTU5MjY1MzU4OTc5M1MxQzFDMEMwUzFDMUMwQzBDMTdDMjVDMjVDMjVDMjVDMEMwQzBDMEMwQzBDMEMwQzBDMEMwQzBDMFMxQzFDMEM3NUMwQzFDMTY1QzFDM0MzQzIwQzdTMUMxQzFDMTQwM1MxQzFDMUM0NDAwQzFDMUMxQzFDMUMyNDAyQzdDMC4wNjI1QzAuMDYyNUMwQzBDMEMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzFDMUMwQzBTMUM1QzVDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzFDMUMwQzBTMEMwQzBDMFMxQzFDNDQ0MDJDMFMxQ0luZmluaXR5QzBDMFMxQzFDSW5maW5pdHlDMFMxQzFDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMUMxQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMxQzFDMEMwUzFDMUMxQzBTMUMxQzQ1Mzc0MjQwQzBTMUMxQzFDMFMxQzFDMjY1MjA2ODE0NjY3MjM4NjRDMFMxQzNDLTFDMFMxQzFDMEMwUzFDMUMwQzBTMUMxQzE1MTdDMFMxQzFDNzUyMkMwUzFDMUMwQzBTMUMxQzFDMFMxQzFDMEMwUzFDMUMxZSUyNTJCMTU1QzBTMUMxQzFlJTI1MkIyNTJDMFMxQzFDMjg0OEMwUzFDMUMwQzBTMUMxQzBDMFMxQzFDMEMwUzFDMUMxQzBTMUMxQzFDMFMxQzFDMEMwUzFDMUMxNjVDMFMxQzFDMEMwUzFDMUMxQzBTMUMxQzFDMFMxQzFDMEMwUzBDMEMwQzBTMUMwQzBDMFMxQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMxQzFDMC4wMDAyNjc5OTk5OTk5OTk5OTk3NEMwUzBDMEMwQzBTMUMxQzBDMFMxQzFDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMxQzBDMEMwUzBDMEMwQzBTMUMwQzBDMFMwQzBDMEMwUzBDMEMwQzBDMEMwUzBDMEMwQzBDMEMwUzFDMUMwQzBTMEMwQzBDMEMwQzBTMEMwQzBDMEMwQzBTMEMwQzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMxQzFDMzFDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMxQzFDMEMwQzE5QzM4OEMyNTZDMzA3QzI4M0MzMDRDMzEwQzMwOUMzMTdDMjUyQzMwNkMyMjBDMTQ3QzIyN0MxODZDMTMyQzI1NUMyMzBDMjkwQzMyNlMwQzBDMEMwUzFDMUMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwUzBDMEMwQzBTMEMwQzBDMFMwQzBDMEMwU1AxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMDExMTExMDAwMDAwMDAxMTAxMDAwMDAwMFBQNzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3MTAxMDEwMTAxMDEwMTAxMDAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDEwMDAwMDAwMDAwMDEwMDAwMDAwMDAwMDEwMTAwMDAwMTAwMDAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwUDFTM1MwQzFDMC4wNjI1QzAuMDYyNUMwU2RTZFA=

**Comment by LuminousLeopards** [comment]
It's because with ASHF the original price gets divided by 12.5 and those only cost 10 diamonds, and the cost is floored so it ends up as 0. I don't think it should be changed as early Dragon stages are difficult enough as is.

**Comment by pickten** [comment]
Oh. That's what I thought initially, but I didn't see the notif that I lost it, and was able to get it back right after buying both. It's a bit weird, though, having something be free with ASHF but not without.

**Comment by EPSIL0N** [comment]
Not trying to be contrary as it works out the same in the end. Referencing the code it is actually two smaller than 1 multipliers and then a max to zero if the value is less than 0e1.

0.2 from Family Discount and (1 - ASHF) and then the max so it is rare that something is small enough to be completely removed.
