### ISSUE TITLE
Stuck moving layout?

### ISSUE THREAD

**Issue by jacobmix** [eternaldensity/Sandcastle-Builder#1490]
If i move something with "Lock Layout" off. (by clicking on anything)
It stays on the mouse, and i can't place it anywhere. Clicking does nothing.
Am i missing something?
Using Chrome version 58.0.3029.110 (64-bit) on Windows 7 (64-bit)

**Comment by eternaldensity** [comment]
Can you postbin a save?

**Comment by jacobmix** [comment]
Sorry for the wait. Here's my save tho: 
https://pastebin.com/wgrzUhDb
