### ISSUE TITLE
Game breaking bug (Not a Priest)

### ISSUE THREAD

**Issue by sfe455** [eternaldensity/Sandcastle-Builder#1505]
The game-breaking bug that prevents you from disabling Not a Priest and in turn prevents you from upgrading Photoelectricity and continuing the game, has apparently been fixed MONTHS ago and it's a super simple error... but it's still not live. Please push it to the game. I don't know how github works. Thank you.

https://www.reddit.com/r/SandcastleBuilder/comments/7g4xg6/game_error_on_triggering_photoelectricity/

**Comment by eternaldensity** [comment]
Fixed in https://github.com/eternaldensity/Sandcastle-Builder/pull/1489
