### ISSUE TITLE
Log autoscroll not working

### ISSUE THREAD

**Issue by eternaldensity** [eternaldensity/Sandcastle-Builder#1520]
Pastebin: https://pastebin.com/wPHWFxWp
Toggling autoscroll is not making autoscroll work.

(via twitter dm)

**Comment by kitocole** [comment]
Thank you for posting this! 

Here is an imgur link to a screenshot: https://imgur.com/a/Rcj3Os0

You can also import and spam question qubes to test here is a new save: https://pastebin.com/5JCGpWwW

**Comment by eternaldensity** [comment]
Ah that didn't survive this https://github.com/eternaldensity/Sandcastle-Builder/commit/2af98cf0938f257a4eaaff3260c370a0eea3c03b
Fixed in version 4.09
