### ISSUE TITLE
Typo prevents `Safety Canary` from reducing `Annilment` to 0

### ISSUE THREAD

**Issue by jaahay** [eternaldensity/Sandcastle-Builder#1523]
https://github.com/eternaldensity/Sandcastle-Builder/blob/48a0ad162e6081a9c2abe5f0eb53cbf501da56fb/boosts.js#L12012

**Comment by eternaldensity** [comment]
So I guess this got fixed by that merge.

**Comment by jaahay** [comment]
Yes, thank you
