### ISSUE TITLE
There aren't any incremental games with complex numbers.

### ISSUE THREAD

**Issue by Prezombie** [eternaldensity/Sandcastle-Builder#178]
Seems like a suitably xkcdish thing to do, applying a transformation on the complex plane to produce _x_ + _y i_ sand per second.

I imagine that imaginary sand would buy weird boosts that would vanish as soon as you  stopped thinking about it, ie ONG or making a purchace.

**Comment by eternaldensity** [comment]
http://timelessriver.net/hyperwaitforce/complexclicker/

@Prezombie 
It's still preliminary but it exists.
